name: ACM Membership Portal
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - run: npm ci
      - run: npm run check
  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - run: npm ci
      - run: npm run eslint
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - run: npm ci
      - run: npm run build
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}
      NEXT_PUBLIC_GOOGLE_CALENDAR_EMAIL: ${{secrets.NEXT_PUBLIC_GOOGLE_CALENDAR_EMAIL}}
      NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY}}
      NEXT_PUBLIC_SHEET_ID: ${{secrets.NEXT_PUBLIC_SHEET_ID}}
      NEXT_PUBLIC_PROJECT_ID: ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
      NEXT_PUBLIC_PRIVATE_KEY_ID: ${{secrets.NEXT_PUBLIC_PRIVATE_KEY_ID}}
      NEXT_PUBLIC_PRIVATE_KEY: ${{secrets.NEXT_PUBLIC_PRIVATE_KEY}}
      NEXT_PUBLIC_CLIENT_EMAIL: ${{secrets.NEXT_PUBLIC_CLIENT_EMAIL}}
      NEXT_PUBLIC_CLIENT_ID: ${{secrets.NEXT_PUBLIC_CLIENT_ID}}
      NEXT_PUBLIC_AUTH_URI: ${{secrets.NEXT_PUBLIC_AUTH_URI}}
      NEXT_PUBLIC_TOKEN_URI: ${{secrets.NEXT_PUBLIC_TOKEN_URI}}
      NEXT_PUBLIC_AUTH_PROVIDER: ${{secrets.NEXT_PUBLIC_AUTH_PROVIDER}}
      NEXT_PUBLIC_CERT_URL: ${{secrets.NEXT_PUBLIC_CERT_URL}}
